make FormErrorHandler more easily extendable
I wanted to override FormErrorHandler so it would return error messages in the format

    error:
        message: Parsed error message
        template: Error message template
        parameters: Error message parameters

instead of

   error: Parsed error message

and it's pretty hard to do with private members.